# Generated by Django 4.2 on 2024-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logi',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
