# Generated by Django 4.2 on 2024-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_logi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('n3', models.IntegerField()),
                ('n4', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
