# Generated by Django 5.0.1 on 2024-02-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shop_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('emaill', models.EmailField(max_length=254)),
                ('proof', models.FileField(upload_to='')),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('action', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
