# Generated by Django 5.0.1 on 2024-02-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_price1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='price1',
        ),
        migrations.AddField(
            model_name='price',
            name='n1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='n2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='n3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='n4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
