# Generated by Django 5.0.1 on 2024-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_price1_price_n1_price_n2_price_n3_price_n4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop1',
        ),
        migrations.AddField(
            model_name='price',
            name='p1',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='p2',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='p3',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='p4',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
