# Generated by Django 5.0.1 on 2024-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_shop1_price_p1_price_p2_price_p3_price_p4'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('nme', models.CharField(max_length=20)),
            ],
        ),
    ]
