# Generated by Django 5.0.1 on 2024-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='action',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
