# Generated by Django 5.0.1 on 2024-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_employee_deliver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop',
        ),
        migrations.AddField(
            model_name='price',
            name='q1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='q2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='q3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='q4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
