# Generated by Django 5.0.1 on 2024-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_shop_price_q1_price_q2_price_q3_price_q4'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
