# Generated by Django 5.0.1 on 2024-02-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
