# Generated by Django 5.0.1 on 2024-02-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
