# Generated by Django 5.0.1 on 2024-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='q1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='q2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='q3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='q4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
