# Generated by Django 5.0.1 on 2024-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
