# Generated by Django 5.0.1 on 2024-02-21 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_cancel_phone_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='datee',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='datee',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
