# Generated by Django 5.0.2 on 2024-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_detail_datee_orders_datee'),
    ]

    operations = [
        migrations.CreateModel(
            name='concent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
