# Generated by Django 5.0.2 on 2024-02-26 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_concent'),
    ]

    operations = [
        migrations.AddField(
            model_name='concent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
